'use client';
import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import EventCard from '@/components/EventCard';
import Pagination from '@/components/Pagination';
import { ListFilter } from 'lucide-react';
type Event={_id:string;title:string;description:string;venue:string;category:string;tags:string[];images:string[];ticketTypes:{price:number}[];organizer?:{name?:string}};
function ExploreEventsContent(){const params=useSearchParams();const [events,setEvents]=useState<Event[]>([]);const [loading,setLoading]=useState(true);const [showFilters,setShowFilters]=useState(false);const [category,setCategory]=useState(params.get('category')??'');
 useEffect(()=>{const query=new URLSearchParams({status:'published',pageSize:'100'});const search=params.get('query');if(search)query.set('search',search);if(category)query.set('category',category);fetch(`/api/events?${query}`).then(r=>r.json()).then(r=>setEvents(r.success?r.data.items:[])).finally(()=>setLoading(false))},[params,category]);
 return <section className='text-text-dark my-10 mx-5 px-4'><div className='flex flex-row items-center'><h2 className='text-3xl font-semibold text-text-dark font-dynapuff'>Explore Events</h2></div><div className='flex justify-end gap-4 mb-4 mt-2 cursor-pointer'><ListFilter onClick={()=>setShowFilters(!showFilters)}/></div>{showFilters&&<div className='flex gap-4 mb-6 p-4 border border-brown-normal rounded-xl bg-brown-light'><select value={category} onChange={e=>setCategory(e.target.value)} className='border border-brown-normal rounded-lg px-3 py-2 bg-white text-sm'><option value=''>All Categories</option>{[...new Set(events.map(event=>event.category))].map(value=><option key={value} value={value}>{value}</option>)}</select></div>} {loading?<p>Loading events…</p>:<div className='grid grid-cols-1 gap-y-9 gap-x-17 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 lg:gap-3 xl:grid-cols-4 2xl:grid-cols-4'>{events.map(event=><EventCard key={event._id} eventId={event._id} tags={event.tags} imageUrl={event.images[0]??'/images/party.png'} imageAlt={event.title} title={event.title} organizer={`By ${event.organizer?.name??'Event organizer'}`} descriptions={[event.description]} location={event.venue} price={event.ticketTypes.some(ticket=>ticket.price===0)?'Free':`From Rs.${Math.min(...event.ticketTypes.map(ticket=>ticket.price))}`}/>)}</div>}<div className='mt-6'><Pagination/></div></section>}
export default function Page(){return <Suspense fallback={<div className='px-5 py-10 text-text-muted'>Loading events…</div>}><ExploreEventsContent/></Suspense>}
