'use client';

import { useCallback, useEffect, useState } from 'react';
import SavedEventsCard from '@/components/SavedEventsCard';
import Pagination from '@/components/Pagination';
import Button from '@/components/Button';

type Event = { _id: string; title: string; venue: string; startDate: string; category: string; ticketTypes: { price: number }[] };
type Item = { event: Event };

export default function Page() {
    const [items, setItems] = useState<Item[]>([]), [page, setPage] = useState(1), [pages, setPages] = useState(1), [q, setQ] = useState(''), [category, setCategory] = useState(''), [date, setDate] = useState(''), [time, setTime] = useState(''), [free, setFree] = useState(''), [loading, setLoading] = useState(true);
    const load = useCallback(async () => { setLoading(true); const params = new URLSearchParams({ page: String(page), pageSize: '12' }); if (q) params.set('q', q); if (category) params.set('category', category); if (date) params.set('date', date); if (time) params.set('time', time); if (free) params.set('free', free); const response = await fetch(`/api/saved-events?${params}`); const result = await response.json(); if (result.success) { setItems(result.data.items); setPages(result.data.totalPages); } setLoading(false); }, [page, q, category, date, time, free]);
    useEffect(() => { const timer = setTimeout(() => void load(), 200); return () => clearTimeout(timer); }, [load]);
    const reset = () => { setQ(''); setCategory(''); setDate(''); setTime(''); setFree(''); setPage(1); };
    const remove = async (eventId: string) => { await fetch('/api/saved-events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ eventId }) }); void load(); };
    return <section className='flex flex-col my-4 mx-2 px-4 font-cause text-text-dark md:mx-3 lg:mx-4 xl:mx-6'><h1 className='font-dynapuff text-2xl md:text-3xl font-bold'>Saved Events</h1><div className='mt-5 flex flex-wrap items-end gap-3'><label className='text-sm'>Search<input value={q} onChange={(event) => { setQ(event.target.value); setPage(1); }} placeholder='Search saved events' className='mt-1 block rounded-lg border border-brown-normal px-3 py-2' /></label><label className='text-sm'>Category<input value={category} onChange={(event) => { setCategory(event.target.value); setPage(1); }} placeholder='art_theater' className='mt-1 block rounded-lg border border-brown-normal px-3 py-2' /></label><label className='text-sm'>Date<input type='date' value={date} onChange={(event) => { setDate(event.target.value); setPage(1); }} className='mt-1 block rounded-lg border border-brown-normal px-3 py-2' /></label><select value={time} onChange={(event) => { setTime(event.target.value); setPage(1); }} className='rounded-lg border border-brown-normal px-3 py-2'><option value=''>Any time</option><option value='upcoming'>Upcoming</option><option value='past'>Past</option></select><select value={free} onChange={(event) => { setFree(event.target.value); setPage(1); }} className='rounded-lg border border-brown-normal px-3 py-2'><option value=''>Any price</option><option value='true'>Free</option><option value='false'>Paid</option></select><Button text='Reset' variant='secondary' size='sm' onClick={reset} /></div>{loading ? <p className='mt-6'>Loading saved events...</p> : items.length === 0 ? <p className='mt-6 rounded-xl border border-brown-normal p-6 text-center'>No saved events found.</p> : <div className='border border-brown-normal rounded-xl mt-6 p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6'>{items.map(({ event }) => <SavedEventsCard key={event._id} eventId={event._id} title={event.title} date={new Date(event.startDate).toLocaleDateString()} location={event.venue} price={Math.min(...event.ticketTypes.map((ticket) => ticket.price))} onRemove={() => void remove(event._id)} />)}</div>}<div className='mt-6'><Pagination page={page} totalPages={pages} onPageChange={setPage} /></div></section>;
}
