"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Calendar, CheckCircle2, Clock, Eye, MapPin, Store, TriangleAlert } from "lucide-react";
import DashboardBox from "@/components/DashboardBox";
import VendorCards from "@/components/VendorCards";
import Button from "@/components/Button";

type EventSummary = { _id: string; title: string; startDate: string; venue: string; images?: string[] };
type Booking = { event: EventSummary | null; stallName?: string; status: "pending" | "confirmed" | "cancelled" };
type DashboardData = { vendor: { businessName: string; approvalStatus: string }; summary: { activeBookingsCount: number; upcomingEventsCount: number; activeEventsCount: number; completedEventsCount: number }; bookings: Booking[] };
const state = (status: Booking["status"]) => status === "confirmed" ? "success" : status === "pending" ? "warning" : "danger";

export default function VendorDashboardPage() {
	const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState("");
	useEffect(() => { let active = true; fetch("/api/vendors/dashboard", { cache: "no-store" }).then(async (r) => { const j = await r.json(); if (!r.ok || !j.success) throw new Error(j.error?.message || "Unable to load vendor dashboard."); if (active) setData(j.data); }).catch((e) => active && setError(e instanceof Error ? e.message : "Unable to load vendor dashboard.")); return () => { active = false; }; }, []);
	const bookings = (data?.bookings ?? []).filter((b) => b.event && b.status !== "cancelled").sort((a, b) => new Date(a.event!.startDate).getTime() - new Date(b.event!.startDate).getTime());
	return <section className="my-4 mx-2 flex flex-col px-4 font-cause text-text-dark md:mx-3 lg:mx-4 xl:mx-6 2xl:mx-8">
		<DashboardBox title="Vendor Dashboard" description={data ? `Manage ${data.vendor.businessName} and its assigned event stalls.` : "Loading your assigned events..."} buttonText="View My Events" buttonLink="/vendor/events" buttonIcon={<Store size={17} />} />
		{error && <div className="mt-6 rounded-xl border border-red-300 bg-red-50 p-4 text-red-700"><TriangleAlert className="mr-2 inline" size={18} />{error}</div>}
		{data && <><>{data.vendor.approvalStatus !== "approved" && <div className="mt-6 rounded-xl border border-amber-300 bg-amber-50 p-4 text-amber-800"><Clock className="mr-2 inline" size={18} />Your vendor profile is {data.vendor.approvalStatus}. Stall booking is available after approval.</div>}</><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><VendorCards icon1={<Store className="text-primary" />} count={data.summary.activeBookingsCount} label="Associated Events" subLabel="Active stall associations" /><VendorCards icon1={<Calendar className="text-blue-500" />} count={data.summary.upcomingEventsCount} label="Upcoming Events" subLabel="Assigned future events" /><VendorCards icon1={<Clock className="text-green-500" />} count={data.summary.activeEventsCount} label="Active Events" subLabel="Events happening now" /><VendorCards icon1={<CheckCircle2 className="text-purple-500" />} count={data.summary.completedEventsCount} label="Completed Events" subLabel="Past assigned events" /></div>
		<div className="mt-10"><div className="flex items-center justify-between gap-4"><h2 className="text-xl font-bold md:text-2xl">Assigned Events</h2><Link href="/vendor/events"><Button text="View All" variant="secondary" size="sm" /></Link></div>{bookings.length === 0 ? <div className="mt-6 rounded-xl border border-brown-normal p-8 text-center"><p className="font-semibold">No assigned events yet.</p><p className="mt-1 text-sm text-text-light">Your approved stall bookings will appear here.</p></div> : <div className="mt-6 grid grid-cols-1 gap-4 xl:grid-cols-2">{bookings.slice(0, 4).map((b) => <article key={b.event!._id} className="rounded-xl border border-brown-normal p-4"><div className="flex flex-col gap-4 sm:flex-row"><div className="h-28 w-full overflow-hidden rounded-xl bg-brown-light sm:w-40">{b.event!.images?.[0] && <img src={b.event!.images[0]} alt="" className="h-full w-full object-cover" />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="font-bold">{b.event!.title}</h3><Button text={b.status} variant="tag" size="vsm" status={state(b.status)} /></div><p className="mt-2 text-sm"><Calendar className="mr-1 inline" size={15} />{new Date(b.event!.startDate).toLocaleString()}</p><p className="mt-1 text-sm"><MapPin className="mr-1 inline" size={15} />{b.event!.venue}</p>{b.stallName && <p className="mt-1 text-sm text-text-light">{b.stallName}</p>}</div></div><div className="mt-4 flex justify-end"><Link href={`/vendor/events/${b.event!._id}`}><Button text="View Details" size="sm" iconLeft={<Eye size={16} />} /></Link></div></article>)}</div>}</div></>}
	</section>;
}
