'use client';

import { useState } from 'react';

type TicketPreview = { state: 'valid' | 'used' | 'cancelled' | 'invalid'; ticketNumber?: string; ticketType?: string; attendee?: { name: string }; event?: { title: string; venue: string }; checkedInAt?: string; checker?: string; message?: string };

export default function TicketLookup({ title, description }: { title: string; description: string }) {
    const [identifier, setIdentifier] = useState(''); const [ticket, setTicket] = useState<TicketPreview | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
    const search = async () => { if (!identifier.trim()) return; setLoading(true); setError(''); setTicket(null); try { const res = await fetch(`/api/checkin?identifier=${encodeURIComponent(identifier.trim())}`); const json = await res.json(); if (!res.ok || !json.success) throw new Error(json.error?.message ?? 'Ticket not found.'); setTicket(json.data); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to verify ticket.'); } finally { setLoading(false); } };
    const checkIn = async () => { setLoading(true); setError(''); try { const res = await fetch('/api/checkin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identifier }) }); const json = await res.json(); if (!res.ok || !json.success) throw new Error(json.error?.message ?? 'Check-in failed.'); setTicket({ ...json.data, state: 'valid', checker: 'You' }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Check-in failed.'); } finally { setLoading(false); } };
    const color = ticket?.state === 'valid' ? 'border-green-300 bg-green-50' : ticket?.state === 'used' ? 'border-amber-300 bg-amber-50' : 'border-red-300 bg-red-50';
    return <section className="mx-auto max-w-2xl px-4 py-10 font-cause text-text-dark"><h1 className="text-3xl font-dynapuff font-semibold">{title}</h1><p className="mb-6 mt-1 text-text-light">{description}</p><div className="rounded-2xl border border-border bg-surface p-5"><label className="mb-2 block text-sm font-medium">Ticket ID / Ticket Code</label><div className="flex gap-2"><input value={identifier} onChange={(e) => setIdentifier(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && void search()} placeholder="VIVNT-... or QR value" className="min-w-0 flex-1 rounded-lg border border-border px-3 py-2" /><button disabled={loading || !identifier.trim()} onClick={() => void search()} className="rounded-lg bg-primary px-4 py-2 text-white disabled:opacity-50">{loading ? 'Loading…' : 'Search Ticket'}</button></div>{error && <p className="mt-4 text-sm text-error">{error}</p>}{ticket && <div className={`mt-5 rounded-xl border p-4 ${color}`}><h2 className="font-semibold">{ticket.state === 'valid' ? '✓ Valid Ticket' : ticket.state === 'used' ? '⚠ Already Checked In' : ticket.state === 'cancelled' ? '✕ Cancelled Ticket' : '✕ Invalid Ticket'}</h2>{ticket.ticketNumber && <div className="mt-3 space-y-1 text-sm"><p><b>Ticket:</b> {ticket.ticketNumber}</p><p><b>Attendee:</b> {ticket.attendee?.name}</p><p><b>Event:</b> {ticket.event?.title}</p><p><b>Ticket type:</b> {ticket.ticketType}</p>{ticket.checkedInAt && <p><b>Checked in:</b> {new Date(ticket.checkedInAt).toLocaleString()} {ticket.checker ? `by ${ticket.checker}` : ''}</p>}</div>}{ticket.message && <p className="mt-2 text-sm">{ticket.message}</p>}{ticket.state === 'valid' && <button disabled={loading} onClick={() => void checkIn()} className="mt-4 rounded-lg bg-primary px-4 py-2 text-white disabled:opacity-50">Confirm Check-In</button>}</div>}</div></section>;
}
