'use client';

import Link from 'next/link';
import { useState } from 'react';
import { signIn } from 'next-auth/react';
import { Eye, EyeOff } from 'lucide-react';
import GoogleIcon from '@mui/icons-material/Google';
import GitHubIcon from '@mui/icons-material/GitHub';
import AuthShell from '@/components/AuthShell';
import Button from '@/components/Button';

export default function Page() {
    const [role, setRole] = useState<'attendee' | 'organizer' | 'vendor'>('attendee');
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [terms, setTerms] = useState(false);
    const [showPassword, setShowPassword] = useState(false);
    const [error, setError] = useState('');
    const [busy, setBusy] = useState(false);
    const register = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (name.trim().length < 3 || password.length < 8 || !terms) { setError('Enter your name, use a password of at least 8 characters, and accept the terms.'); return; } setBusy(true); const response = await fetch('/api/auth/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email, password, role }) }); const result = await response.json(); if (!response.ok || !result.success) { setError(result.error?.message ?? 'Unable to create account.'); setBusy(false); return; } const login = await signIn('credentials', { email, password, redirect: false }); if (login?.error) { setError('Account created but sign in failed.'); setBusy(false); return; } window.location.assign(role === 'organizer' ? '/organizerdashboard' : role === 'vendor' ? '/vendordashboard' : '/userdashboard'); };
    const oauth = async (provider: 'google' | 'github') => { setError(''); const result = await signIn(provider, { callbackUrl: '/' }); if (result?.error) setError('Unable to sign in with this provider.'); };
    return <AuthShell title="Create your account" subtitle="Choose how you want to use Vivnt, then join a community built around real experiences." footer={<>Already have an account? <Link href="/login" className="font-semibold text-brown-dark hover:underline">Sign in</Link></>}><div className="space-y-3"><button type="button" onClick={() => void oauth('google')} className="flex w-full items-center justify-center gap-3 rounded-xl border border-border px-4 py-3 font-semibold transition hover:bg-surface-hover"><GoogleIcon fontSize="small" /> Continue with Google</button><button type="button" onClick={() => void oauth('github')} className="flex w-full items-center justify-center gap-3 rounded-xl border border-border px-4 py-3 font-semibold transition hover:bg-surface-hover"><GitHubIcon fontSize="small" /> Continue with GitHub</button></div><div className="my-7 flex items-center gap-3 text-xs uppercase tracking-widest text-text-muted"><span className="h-px flex-1 bg-divider" />or email<span className="h-px flex-1 bg-divider" /></div><form onSubmit={register} className="space-y-5"><label className="block text-sm font-semibold">I want to<div className="mt-2 grid grid-cols-3 gap-2">{(['attendee', 'organizer', 'vendor'] as const).map((item) => <button key={item} type="button" onClick={() => setRole(item)} className={`rounded-lg border px-2 py-2 text-xs font-semibold capitalize ${role === item ? 'border-brown-dark bg-brown-light text-brown-dark' : 'border-border'}`}>{item}</button>)}</div></label><label className="block text-sm font-semibold">Full name<input required value={name} onChange={(event) => setName(event.target.value)} className="form-control mt-2" placeholder="Your name" /></label><label className="block text-sm font-semibold">Email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="form-control mt-2" placeholder="you@example.com" /></label><label className="block text-sm font-semibold">Password<div className="relative mt-2"><input required minLength={8} type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} className="form-control pr-10" placeholder="At least 8 characters" /><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Hide password' : 'Show password'} className="absolute right-3 top-3">{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><label className="flex items-start gap-2 text-sm text-text-light"><input required type="checkbox" checked={terms} onChange={(event) => setTerms(event.target.checked)} /><span>I agree to the Terms and Conditions.</span></label>{error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<Button text={busy ? 'Creating account...' : 'Create account'} type="submit" variant="cta" className="w-full" disabled={busy} /></form></AuthShell>;
}
